name: setup-mysql-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.label.name == 'skip-ci' }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
