#name: Test Runs On
#
#on: [workflow_dispatch]
#
#env:
#  runs_on: ubuntu-latest
#
#jobs:
#  test-runs-on:
#    strategy:
#      matrix:
#        runs_on: [ubuntu-latest, macos-latest, windows-latest]
#        jdk: [11, 19]
#        exclude:
#          - runs_on: macos-latest
#          - runs_on: windows-latest
#          - jdk: 19
#    runs-on: ${{ matrix.runs_on }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: ${{ matrix.jdk }}
#      - name: Echo Hello
#        run: echo "Hello World"
