name: Test Runs on

on: [push, pull_request, workflow_dispatch]

env:
  runs_on: ubuntu-latest

jobs:
  run:
    runs-on: ${{ vars.runs_on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Retrieve SpotBugs report list
        run: echo "Hello World"
