name: Test Env
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Retrieve SpotBugs report list
        run: |
          find . -name \"*Test.java\" -exec printf "%s," {} + | sed 's/,$//'
          echo "SPOTBUGS_LIST=$(find . -name spotbugsXml.xml -exec printf "%s," {} + | sed 's/,$//')" >> $GITHUB_OUTPUT
      - name: upload to SonarCloud
        run: echo ${{ steps.version.outputs.SPOTBUGS_LIST }}