name: Test Runs On

on: [push, pull_request, workflow_dispatch]

env:
  runs_on: ubuntu-latest

jobs:
  test-runs-on:
    strategy:
      matrix:
        runs_on: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - runs_on: macos-latest windows-latest
    runs-on: ${{ matrix.runs_on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Echo Hello
        run: echo "Hello World"
