name: Test Runs on

on: [push, pull_request, workflow_dispatch]

env:
  runs_on: ubuntu-latest

jobs:
  run:
    runs-on: ${{env.runs_on}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Retrieve SpotBugs report list
        run: |
          find . -name pom.xml -exec printf "%s," {} + | sed 's/,$//'
          echo "SPOTBUGS_LIST=$(find . -name pom.xml -exec printf "%s," {} + | sed 's/,$//')" >> $GITHUB_ENV
      - name: upload to SonarCloud
        run: echo ${SPOTBUGS_LIST}
